import { BrowserContext, Page } from '@playwright/test';
import {
  TEST_BITCOIN_CONTRACT_ATTESTOR_URLS,
  TEST_BITCOIN_CONTRACT_COUNTERPARTYWALLETDETAILS,
  TEST_BITCOIN_CONTRACT_OFFER,
} from '@tests/mocks/constants';
import { BitcoinContractRequestSelectors } from '@tests/selectors/bitcoin-contract-request.selectors';
import { SettingsSelectors } from '@tests/selectors/settings.selectors';

import { test } from '../../fixtures/fixtures';

const requestParams = {
  bitcoinContractOffer: TEST_BITCOIN_CONTRACT_OFFER,
  attestorURLs: TEST_BITCOIN_CONTRACT_ATTESTOR_URLS,
  counterpartyWalletDetails: TEST_BITCOIN_CONTRACT_COUNTERPARTYWALLETDETAILS,
};

const storageMockResponse200 = {
  id: 2071,
  uuid: '0xe5f5351480d17c5df98a7bba4955f64a7dcfd5dc24a5ac14fb3cafdedfea03c2',
  state: 'accepted',
  content:
    'Al4Zu4tkO0Y4mG4hhMKZ/GZLSyNjwEozst9Vts6STxY8AAEBAgACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAnEAAAAAIAAAAAAAAAZAAAAAAAACcQAAAAAAAAAAA//wAAAAAAACcQAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAgMAAAAAAAAADgAAAAAAAAAOAAAAAAAAAA4DVoIyMertZp5fb/Me0CF07c8SsBZD5S5J0P5U3MAKoeFmsiNrJEipG6Hd89HMAh6dA1zRWuIMUxW47SW+/V2O6qvko3nXTr0JGoz2/U7ZrbMTb7oXRwvy/xjHR4dYltD5/dgi/QIdAA5McgCRJh5FL9vq002z4B1JXOAVJlRs8lj75sKl1wGw/m+N9svpguj2sKNHyLq9Oi+LVkBitdV7oMbRg32TwEUuSlIXDIXCSFAz1MfgH9glpUpMXPnSe4Ef7byjYkJWglcE2IPIkaHlYhfVJqAh1QsDFhEKJeMjCUxbZ3b1HjB++WbBJJ9VoxBDf0ipT/n1X2SxbYqQJSN3qI2J5Mtkm0shcXSvG51B0Hxkf/HuMlN5x8Irb/EY7ZFTB9UbdwqSZI23IoJqsOQFPLNVSEj2wfNXc8tepUWj7v0A4U4Z+rEEEz48B6NiWn3jvmfbGhAzxls37qWrZw6APAKvkPjDRxA0bKaiW0/t1LbnDjmshJTGzTor0YySy0SQsnfLQpK2txY/0SWWTw+wzxCwBcN/txDxeA87e6uS9hf8d9P99wgnK0RryscKBJpqxkEOAF6aRqWI5C5jvAqy5kfsCGGNQfB2Rd7HkqpgOYliy+vBnCUT7jJy4dnjrQB75k3ryFtw8W6OQBpRlQt++/ZmWsr7SjpVzIccjllJCoD2sFAn7sGswyJBhNc4JcqUjVGhaf8k8dlbZxQBLOTY3DJne0ATudw1ZbisCP3YChAAAgAGQlRDVVNEAAAAAAAOQjB4MTAxMDJhNDRiOWI3NThiNmMwZGJjMDdiMDE5YmMyODM4M2QxN2IyMTA0ZTc3YWEwZDMwYTc1NTVmMTc2MjkyZogV01V7eKZpFf3G+eG7Hzt+KRGkTZ5QrtpixOw9iSI/ijGcYOneDxtAakrxVxdAJmK4emyg1+HGCO91F8h7/AqJhQj58kapwmSEaxZY2/WPs739JOfcqnGhQ+vv/lAldf3YIv0CHQAO2LBC2rax+fPaIGv+IeHkFw3qznsYfckwt4lZctdSM5ax8gR85qtlc42gxvfsPbolPxBOOQgzKlXSL0ioyGVwiPSpnKXfvd5eFQbW8gCzCojSFlbNmoxKY3JSNmgxrt6nUoxqyfCGZCyDQJUxp+UFek9BSBGH9SCR4Vz8dl2tFKgeLXG3edH319R19+H40O64vK6UfSVMl5l/29f/EePNohu1XYiroIIcCI4L6AohpWv4ozzWvuKO2YpVMpMbSY4V6vkQiLmH+EBWEfdtubgxkiH0AlToCeG23x5Dr4jkd9cUKqSvg91b0KX9wbXnWClDUWWoNFgxtn+T9g/L1BPjQobb2v4nhclx1T4dbQ9SnckXXXI7vULlcaB5Mjbhd9ROG5Y5dcexMp3cQQz/+hydA0xIHwkphW0rbqtzDVZ6jHKi+NYqPOjO5FJCuRW47/yB/yaNuT/f+uVcb0n5pEK9xBPGaEeAEeWESIPrUu95QZFGBs4cEuEUPnHTGYH0aGiaiXhM3EedoKZ8htBixEOAuQNToQ9kLXwNjliYvCU80bw+jWapBDve0vwHCzWnHbGZO9IL1iGuJyZ/di6SAbDi0GW4rAj92AoQAAIABkJUQ1VTRAAAAAAADkIweDEwMTAyYTQ0YjliNzU4YjZjMGRiYzA3YjAxOWJjMjgzODNkMTdiMjEwNGU3N2FhMGQzMGE3NTU1ZjE3NjI5MmZ2mxhERe8aQBNfIArCMfddc/9avYDuxzTedyPOWnnlNeXtBYqVwpDqnwArZAczeVm9fNeV9DIzHIxMowfX5inA7X+plKoLvvVweTzyNK1k5Yb5JYCM18Rc+Wzv7qtAFZX92CL9Ah0ADh3sb4z6DWTHX2JhlBFjXXIpJ+Z8enTnUMFgQc3gonC1adpea0RFO17fOtOhlO06iDqkgTlwrOhZCLctQrOuioLCad/mKNA0S5ZslC1bMMCKY4cHrwl2hbUFtA07na/IZn3FFUE5LQGcZcH6D8sE5A86hYasnYpL+Cr0FFzy1xy3ppqOV9VyCav38mNxwGvGCPXYAqal8Z5O3VU9Ma8zSUURQYKQQb3kUirjgZAkJFiH6uzq6HNs83BZ+6SOcejZyvE5jgz7meXJg/9l2O4a2a9zN6+4AUn91lihgwG+Kuf+oMZ/SKWqG7/s/sLVGh8E0GeshzhTeJ315aN4hET9iotUr7/lMM1POhKiHtzHwYx0Q0D+PYp2hKuAoWnbygd0/BHYKicHrwmBhpnkoKscGvLuxlJFWaHy6dop1VYnZsx+bSzClL0/ScebT97p5r1PjlgR5He6kjspA5tR0PUldnOhOeq+A77ey4ZtBze8gkIE0WSAfD7e6C4sToAG6oPCFFsjbOE2pQjuWjpfDrXiaCErrm5dU9V0hmeHdi0baXwGn9pqnnfzcABJgtXPeYHE72b29B/KFDRZwYV+lHbtziVluKwI/dgKEAACAAZCVENVU0QAAAAAAA5CMHgxMDEwMmE0NGI5Yjc1OGI2YzBkYmMwN2IwMTliYzI4MzgzZDE3YjIxMDRlNzdhYTBkMzBhNzU1NWYxNzYyOTJmAAAAAAAAAAMCKbWNDKaR5i8eo89mp1s/Cyz3rKg9e9Pj2yyIi7jX+soAFgAU0CVKK10XM4eRWKIL19AC7h6EypANRUIsg7So9AAWABTQJUorXRczh5FYogvX0ALuHoTKkGvee7UBNicwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnEAACrj4v51HpoAAAAAAAAAGQZT92S2XB5ogC/I6XQZKGzwXl0TP0H/bVH2kd2gOencAHJFpCHix+xhwDlp/z4r9/L3PckDzRFEIDLIx4EdV9ls4yfuicnt6mP6gAFgAUiL+qs61fLxZOHLtQzQdljM6iZODpCcGYsRIcgwAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4BLDRPqD5OBVAcC5mriolVFLAY+dw7M/CBEagt7EXqtI1YmqXCes/2QUAAAAAQAAAAAAAABrAADh3v+Kz/d7NgAAAAAAA/12AAAAAAAAJxAB4d7/is/3ezb9AX4CAAAAAAECvUrMqBpVXrRD8FLrq6080PhY1UWB4n/OVNeFE0vKORkAAAAAAP/////tOoS1lG9FKmlYaXcOyU4Rh7JRmJoMYGn+L87W1GqvwwMAAAAA/////wLADAEAAAAAACIAIPEkDESjyIYkxfyyLYaojPpbeKXyQ4Uwup6Y9pL4uNuDdv0DAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4AJHMEQCID5dsWY5U6qk1bhjGp1OViugWfjPQcoMeQw+6li4n5rNAiBbZ2DG9e08qaB5SYfL5T0ghmDBEeMTHKvYudsMT/seqAEhA5af8+K/fy9z3JA80RRCAyyMeBHVfZbOMn7onJ7epj+oAkcwRAIgC6cDtBcuTWtMv6nGxVlq3Z+HQEmeLaGdt+QYy8j3NooCIE2mfefYS5M2LRswyAhnyBq9io2pqWQkbCOPUuksd4ghASEDlp/z4r9/L3PckDzRFEIDLIx4EdV9ls4yfuicnt6mP6gAAAAAAAAAAf////8AawAAAQAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4AEBANsBAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAQEAAAAAAAAAAQAAAAAAAAABAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAAAEAAAAAAAAAAQEBAAAAAAAAAAIAAAAAAAAAAgEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAAIBAAAAAAAAAAYBAQAAAAAAAAADAAAAAAAAAAMBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAAADAQAAAAAAAAAFAQEAAAAAAAAABAAAAAAAAAAEAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAABAEAAAAAAAAADAEBAAAAAAAAAAUAAAAAAAAABQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAAcBAAAAAAAAAAkBAQAAAAAAAAAGAAAAAAAAAAYBAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAAAKAQAAAAAAAAAOAQEAAAAAAAAABwAAAAAAAAAHAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAACwEAAAAAAAAADQEBAAAAAAAAAAgAAAAAAAAACAEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAAgBAAAAAAAAABgBAQAAAAAAAAAJAAAAAAAAAAkBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAAAPAQAAAAAAAAARAQEAAAAAAAAACgAAAAAAAAAKAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAEgEAAAAAAAAAFgEBAAAAAAAAAAsAAAAAAAAACwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAABMBAAAAAAAAABUBAQAAAAAAAAAMAAAAAAAAAAwBAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAAAUAQAAAAAAAAAcAQEAAAAAAAAADQAAAAAAAAANAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAFwEAAAAAAAAAGQEBAAAAAAAAAA4AAAAAAAAADgEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAABoBAAAAAAAAAB4BAQAAAAAAAAAPAAAAAAAAAA8BAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAAAbAQAAAAAAAAAdAQEAAAAAAAAAEAAAAAAAAAAQAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAEAEAAAAAAAAAMAEBAAAAAAAAABEAAAAAAAAAEQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAB8BAAAAAAAAACEBAQAAAAAAAAASAAAAAAAAABIBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAAAiAQAAAAAAAAAmAQEAAAAAAAAAEwAAAAAAAAATAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAIwEAAAAAAAAAJQEBAAAAAAAAABQAAAAAAAAAFAEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAACQBAAAAAAAAACwBAQAAAAAAAAAVAAAAAAAAABUBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAAAnAQAAAAAAAAApAQEAAAAAAAAAFgAAAAAAAAAWAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAKgEAAAAAAAAALgEBAAAAAAAAABcAAAAAAAAAFwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAACsBAAAAAAAAAC0BAQAAAAAAAAAYAAAAAAAAABgBAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAAAoAQAAAAAAAAA4AQEAAAAAAAAAGQAAAAAAAAAZAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAALwEAAAAAAAAAMQEBAAAAAAAAABoAAAAAAAAAGgEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAADIBAAAAAAAAADYBAQAAAAAAAAAbAAAAAAAAABsBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAAAzAQAAAAAAAAA1AQEAAAAAAAAAHAAAAAAAAAAcAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAANAEAAAAAAAAAPAEBAAAAAAAAAB0AAAAAAAAAHQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAADcBAAAAAAAAADkBAQAAAAAAAAAeAAAAAAAAAB4BAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAAA6AQAAAAAAAAA+AQEAAAAAAAAAHwAAAAAAAAAfAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAOwEAAAAAAAAAPQEBAAAAAAAAACAAAAAAAAAAIAEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAACABAAAAAAAAAGABAQAAAAAAAAAhAAAAAAAAACEBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAAA/AQAAAAAAAABBAQEAAAAAAAAAIgAAAAAAAAAiAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAQgEAAAAAAAAARgEBAAAAAAAAACMAAAAAAAAAIwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAAEMBAAAAAAAAAEUBAQAAAAAAAAAkAAAAAAAAACQBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAABEAQAAAAAAAABMAQEAAAAAAAAAJQAAAAAAAAAlAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAARwEAAAAAAAAASQEBAAAAAAAAACYAAAAAAAAAJgEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAAEoBAAAAAAAAAE4BAQAAAAAAAAAnAAAAAAAAACcBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAABLAQAAAAAAAABNAQEAAAAAAAAAKAAAAAAAAAAoAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAASAEAAAAAAAAAWAEBAAAAAAAAACkAAAAAAAAAKQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAE8BAAAAAAAAAFEBAQAAAAAAAAAqAAAAAAAAACoBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAABSAQAAAAAAAABWAQEAAAAAAAAAKwAAAAAAAAArAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAUwEAAAAAAAAAVQEBAAAAAAAAACwAAAAAAAAALAEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAAFQBAAAAAAAAAFwBAQAAAAAAAAAtAAAAAAAAAC0BAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAABXAQAAAAAAAABZAQEAAAAAAAAALgAAAAAAAAAuAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAWgEAAAAAAAAAXgEBAAAAAAAAAC8AAAAAAAAALwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAAFsBAAAAAAAAAF0BAQAAAAAAAAAwAAAAAAAAADABAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAABQAQAAAAAAAABwAQEAAAAAAAAAMQAAAAAAAAAxAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAXwEAAAAAAAAAYQEBAAAAAAAAADIAAAAAAAAAMgEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAGIBAAAAAAAAAGYBAQAAAAAAAAAzAAAAAAAAADMBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAABjAQAAAAAAAABlAQEAAAAAAAAANAAAAAAAAAA0AQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAZAEAAAAAAAAAbAEBAAAAAAAAADUAAAAAAAAANQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAGcBAAAAAAAAAGkBAQAAAAAAAAA2AAAAAAAAADYBAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAABqAQAAAAAAAABuAQEAAAAAAAAANwAAAAAAAAA3AQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAawEAAAAAAAAAbQEBAAAAAAAAADgAAAAAAAAAOAEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAAGgBAAAAAAAAAHgBAQAAAAAAAAA5AAAAAAAAADkBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAABvAQAAAAAAAABxAQEAAAAAAAAAOgAAAAAAAAA6AQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAcgEAAAAAAAAAdgEBAAAAAAAAADsAAAAAAAAAOwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAAHMBAAAAAAAAAHUBAQAAAAAAAAA8AAAAAAAAADwBAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAAB0AQAAAAAAAAB8AQEAAAAAAAAAPQAAAAAAAAA9AQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAdwEAAAAAAAAAeQEBAAAAAAAAAD4AAAAAAAAAPgEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAAHoBAAAAAAAAAH4BAQAAAAAAAAA/AAAAAAAAAD8BAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAAB7AQAAAAAAAAB9AQEAAAAAAAAAQAAAAAAAAABAAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAQAEAAAAAAAAAwAEBAAAAAAAAAEEAAAAAAAAAQQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAH8BAAAAAAAAAIEBAQAAAAAAAABCAAAAAAAAAEIBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAACCAQAAAAAAAACGAQEAAAAAAAAAQwAAAAAAAABDAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAgwEAAAAAAAAAhQEBAAAAAAAAAEQAAAAAAAAARAEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAIQBAAAAAAAAAIwBAQAAAAAAAABFAAAAAAAAAEUBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAACHAQAAAAAAAACJAQEAAAAAAAAARgAAAAAAAABGAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAigEAAAAAAAAAjgEBAAAAAAAAAEcAAAAAAAAARwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAAIsBAAAAAAAAAI0BAQAAAAAAAABIAAAAAAAAAEgBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAACIAQAAAAAAAACYAQEAAAAAAAAASQAAAAAAAABJAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAjwEAAAAAAAAAkQEBAAAAAAAAAEoAAAAAAAAASgEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAJIBAAAAAAAAAJYBAQAAAAAAAABLAAAAAAAAAEsBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAACTAQAAAAAAAACVAQEAAAAAAAAATAAAAAAAAABMAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAlAEAAAAAAAAAnAEBAAAAAAAAAE0AAAAAAAAATQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAJcBAAAAAAAAAJkBAQAAAAAAAABOAAAAAAAAAE4BAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAACaAQAAAAAAAACeAQEAAAAAAAAATwAAAAAAAABPAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAmwEAAAAAAAAAnQEBAAAAAAAAAFAAAAAAAAAAUAEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAJABAAAAAAAAALABAQAAAAAAAABRAAAAAAAAAFEBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAACfAQAAAAAAAAChAQEAAAAAAAAAUgAAAAAAAABSAQAAAAAAAAAAAAABAAAAAAAAAAABAgEAAAAAAAAAogEAAAAAAAAApgEBAAAAAAAAAFMAAAAAAAAAUwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAAKMBAAAAAAAAAKUBAQAAAAAAAABUAAAAAAAAAFQBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAACkAQAAAAAAAACsAQEAAAAAAAAAVQAAAAAAAABVAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAApwEAAAAAAAAAqQEBAAAAAAAAAFYAAAAAAAAAVgEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAAKoBAAAAAAAAAK4BAQAAAAAAAABXAAAAAAAAAFcBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAACrAQAAAAAAAACtAQEAAAAAAAAAWAAAAAAAAABYAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAqAEAAAAAAAAAuAEBAAAAAAAAAFkAAAAAAAAAWQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAK8BAAAAAAAAALEBAQAAAAAAAABaAAAAAAAAAFoBAAAAAAAAAAAAAAEAAAAAAAAAAAECAQAAAAAAAACyAQAAAAAAAAC2AQEAAAAAAAAAWwAAAAAAAABbAQAAAAAAAAABAAABAAAAAAAAAAEBAgEAAAAAAAAAswEAAAAAAAAAtQEBAAAAAAAAAFwAAAAAAAAAXAEAAAAAAAAAAAAAAQAAAAAAAAABAQIBAAAAAAAAALQBAAAAAAAAALwBAQAAAAAAAABdAAAAAAAAAF0BAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAAC3AQAAAAAAAAC5AQEAAAAAAAAAXgAAAAAAAABeAQAAAAAAAAAAAAABAAAAAAAAAAEBAgEAAAAAAAAAugEAAAAAAAAAvgEBAAAAAAAAAF8AAAAAAAAAXwEAAAAAAAAAAQAAAQAAAAAAAAABAQIBAAAAAAAAALsBAAAAAAAAAL0BAQAAAAAAAABgAAAAAAAAAGABAAAAAAAAAAAAAAEAAAAAAAAAAQECAQAAAAAAAACgAQAAAAAAAADMAQEAAAAAAAAAYQAAAAAAAABhAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAvwEAAAAAAAAAwQEBAAAAAAAAAGIAAAAAAAAAYgEAAAAAAAAAAAAAAQAAAAAAAAAAAQIBAAAAAAAAAMIBAAAAAAAAAMYBAQAAAAAAAABjAAAAAAAAAGMBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAADDAQAAAAAAAADFAQEAAAAAAAAAZAAAAAAAAABkAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAxAEAAAAAAAAAxwEBAAAAAAAAAGQAAAAAAAAAZQEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAMgBAAAAAAAAAMkBAQAAAAAAAABkAAAAAAAAAGYBAAAAAAAAAAEAAAEAAAAAAAAAAQECAQAAAAAAAADKAQAAAAAAAADLAQEAAAAAAAAAZAAAAAAAAABnAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAAgAEAAAAAAAAAzQEBAAAAAAAAAGQAAAAAAAAAaAEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAAM4BAAAAAAAAAM8BAQAAAAAAAABkAAAAAAAAAGkBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAADQAQAAAAAAAADRAQEAAAAAAAAAZAAAAAAAAABqAQAAAAAAAAABAAABAAAAAAAAAAABAgEAAAAAAAAA0gEAAAAAAAAA0wEBAAAAAAAAAGQAAAAAAAAAawEAAAAAAAAAAQAAAQAAAAAAAAAAAQIBAAAAAAAAANQBAAAAAAAAANUBAQAAAAAAAABkAAAAAAAAAGwBAAAAAAAAAAEAAAEAAAAAAAAAAAECAQAAAAAAAADWAQAAAAAAAADXAQEAAAAAAAAAZAAAAAAAAABtAQAAAAAAAAABAAAAAQIBAAAAAAAAANgBAAAAAAAAANkBAAAAAAAAANoAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAIDAAAAAAAAAA4AAAAAAAAADgAAAAAAAAAOAABFTnpBMlXGNHKJnxG1qlDxuhxNRXEaUwaCBHa9UP3B2mxJvStYuEaCNOJnOQmEaivasz46UiBjglrw2xa4dL9uAgAAAAHAuZq4qJVRSwGPncOzPwgRGoLexF6rSNWJqlwnrP9kFAEAAAAA/////wLADAEAAAAAACIAIFHFxoHgko81UocBvvJ/GNG+JGDFIIfBEQIJofyjf8JWpgECAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4AAAAABlAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wEQJwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BrCYAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4Et2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AUgmAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wHkJQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BgCUAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4Et2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////ARwlAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wG4JAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BVCQAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4Et2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AfAjAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wGMIwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CKCMAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4OgDAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wLEIgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgTAQAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AmAiAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCwBAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C/CEAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4BQFAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKYIQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgeAUAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AjQhAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODcBQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C0CAAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4EAGAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJsIAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgpAYAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AgggAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOAIBwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CpB8AAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4GwHAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJAHwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTg0AcAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AtweAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOA0CAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CeB4AAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4JgIAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wIUHgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTg/AgAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////ArAdAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBgCQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CTB0AAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4MQJAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wLoHAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgKAoAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AoQcAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCMCgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CIBwAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4PAKAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wK8GwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgVAsAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AlgbAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOC4CwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C9BoAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4BwMAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKQGgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTggAwAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AiwaAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODkDAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CyBkAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4EgNAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJkGQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgrA0AAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AgAZAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOAQDgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CnBgAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4HQOAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wI4GAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTg2A4AAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AtQXAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOA8DwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CcBcAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4KAPAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wIMFwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgBBAAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AqgWAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBoEAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CRBYAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4MwQAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wLgFQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgMBEAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AnwVAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCUEQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CGBUAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4PgRAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wK0FAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgXBIAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AlAUAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODAEgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C7BMAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4CQTAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKIEwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgiBMAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AiQTAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODsEwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CwBIAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4FAUAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJcEgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgtBQAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AvgRAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOAYFQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8ClBEAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4HwVAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wIwEQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTg4BUAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AswQAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBEFgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CaBAAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4KgWAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wIEEAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgDBcAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AqAPAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBwFwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CPA8AAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4NQXAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wLYDgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgOBgAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AnQOAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCcGAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CEA4AAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4AAZAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKsDQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgZBkAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AkgNAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODIGQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C5AwAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4CwaAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKADAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgkBoAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AhwMAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOD0GgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CuAsAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4FgbAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJUCwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgvBsAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AvAKAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOAgHAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CjAoAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4IQcAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wIoCgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTg6BwAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AsQJAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOBMHQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CYAkAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4LAdAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wL8CAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgFB4AAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////ApgIAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOB4HgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CNAgAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4NweAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wLQBwAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgQB8AAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AmwHAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCkHwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CCAcAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4AggAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wKkBgAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgbCAAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AkAGAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZODQIAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8C3AUAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4DQhAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJ4BQAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgmCEAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AhQFAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOD8IQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8CsAQAAAAAAAAWABSIv6qzrV8vFk4cu1DNB2WMzqJk4GAiAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wJMBAAAAAAAABYAFIi/qrOtXy8WThy7UM0HZYzOomTgxCIAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AugDAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOAoIwAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BjCMAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AfAjAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wFUJAAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BuCQAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////ARwlAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wGAJQAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8B5CUAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////AUgmAAAAAAAAFgAU0CVKK10XM4eRWKIL19AC7h6EypBLdj9lAgAAAAH+FaVNEBlpJKaf7+S/9oQ2LArMiz5a5GFlOurkn47suwAAAAAA/v///wGsJgAAAAAAABYAFNAlSitdFzOHkViiC9fQAu4ehMqQS3Y/ZQIAAAAB/hWlTRAZaSSmn+/kv/aENiwKzIs+WuRhZTrq5J+O7LsAAAAAAP7///8BECcAAAAAAAAWABTQJUorXRczh5FYogvX0ALuHoTKkEt2P2UCAAAAAf4VpU0QGWkkpp/v5L/2hDYsCsyLPlrkYWU66uSfjuy7AAAAAAD+////ARAnAAAAAAAAFgAUiL+qs61fLxZOHLtQzQdljM6iZOCI5sFlAEdSIQIptY0MppHmLx6jz2anWz8LLPesqD170+PbLIiLuNf6yiEDlp/z4r9/L3PckDzRFEIDLIx4EdV9ls4yfuicnt6mP6hSrg==',
  key: '03fe21e3444109e30ff7d19da0f530c344cad2e35fbee89afb2413858e4a9d7aa5',
};

const blockchainMockResponse = {
  txid: '1464ffac275caa89d548ab5ec4de821a11083fb3c39d8f014b5195a8b89ab9c0',
  version: 2,
  locktime: 0,
  vin: [
    {
      txid: '1939ca4b1385d754ce7fe28145d558f8d03cadabeb52f043b45e551aa8cc4abd',
      vout: 0,
      prevout: {
        scriptpubkey: '001488bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
        scriptpubkey_asm: 'OP_0 OP_PUSHBYTES_20 88bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
        scriptpubkey_type: 'v0_p2wpkh',
        scriptpubkey_address: 'tb1q3zl64vadtuh3vnsuhdgv6pm93n82ye8qc36c07',
        value: 65234,
      },
      scriptsig: '',
      scriptsig_asm: '',
      witness: [
        '304402203e5db1663953aaa4d5b8631a9d4e562ba059f8cf41ca0c790c3eea58b89f9acd02205b6760c6f5ed3ca9a0794987cbe53d208660c111e3131cabd8b9db0c4ffb1ea801',
        '03969ff3e2bf7f2f73dc903cd11442032c8c7811d57d96ce327ee89c9edea63fa8',
      ],
      is_coinbase: false,
      sequence: 4294967295,
    },
    {
      txid: 'c3af6ad4d6ce2ffe69600c9a9851b287114ec90e776958692a456f94b5843aed',
      vout: 3,
      prevout: {
        scriptpubkey: '001488bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
        scriptpubkey_asm: 'OP_0 OP_PUSHBYTES_20 88bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
        scriptpubkey_type: 'v0_p2wpkh',
        scriptpubkey_address: 'tb1q3zl64vadtuh3vnsuhdgv6pm93n82ye8qc36c07',
        value: 353060,
      },
      scriptsig: '',
      scriptsig_asm: '',
      witness: [
        '304402200ba703b4172e4d6b4cbfa9c6c5596add9f8740499e2da19db7e418cbc8f7368a02204da67de7d84b93362d1b30c80867c81abd8a8da9a964246c238f52e92c77882101',
        '03969ff3e2bf7f2f73dc903cd11442032c8c7811d57d96ce327ee89c9edea63fa8',
      ],
      is_coinbase: false,
      sequence: 4294967295,
    },
  ],
  vout: [
    {
      scriptpubkey: '0020f1240c44a3c88624c5fcb22d86a88cfa5b78a5f2438530ba9e98f692f8b8db83',
      scriptpubkey_asm:
        'OP_0 OP_PUSHBYTES_32 f1240c44a3c88624c5fcb22d86a88cfa5b78a5f2438530ba9e98f692f8b8db83',
      scriptpubkey_type: 'v0_p2wsh',
      scriptpubkey_address: 'tb1q7yjqc39rezrzf30ukgkcd2yvlfdh3f0jgwznpw57nrmf979cmwpsrr7xvu',
      value: 68800,
    },
    {
      scriptpubkey: '001488bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
      scriptpubkey_asm: 'OP_0 OP_PUSHBYTES_20 88bfaab3ad5f2f164e1cbb50cd07658ccea264e0',
      scriptpubkey_type: 'v0_p2wpkh',
      scriptpubkey_address: 'tb1q3zl64vadtuh3vnsuhdgv6pm93n82ye8qc36c07',
      value: 261494,
    },
  ],
  size: 382,
  weight: 880,
  fee: 88000,
  status: {
    confirmed: true,
    block_height: 2535476,
    block_hash: '0000000001d073b51f5ed53e1eeb1ef7f885fb3ef2bce1a1c7596f398194ee1c',
    block_time: 1698411283,
  },
};

function initiateOfferRequest(page: Page) {
  return async (requestParams: {
    bitcoinContractOffer: string;
    attestorURLs: string;
    counterpartyWalletDetails: string;
  }) =>
    page.evaluate(
      async params =>
        (window as any).HiroWalletProvider.request('acceptBitcoinContractOffer', params).catch(
          (e: unknown) => e
        ),
      requestParams
    );
}

async function clickReject(context: BrowserContext) {
  const popup = await context.waitForEvent('page');
  await popup.waitForTimeout(500);

  const rejectButton = popup.getByTestId(
    BitcoinContractRequestSelectors.BitcoinContractRejectButton
  );
  await rejectButton.click();
}

test.describe('Bitcoin Contract Request Test', () => {
  test.beforeEach(async ({ extensionId, globalPage, onboardingPage, homePage, page }) => {
    await globalPage.setupAndUseApiCalls(extensionId);
    await onboardingPage.signInWithTestAccount(extensionId);
    await homePage.clickSettingsButton();
    await page.getByTestId(SettingsSelectors.ChangeNetworkAction).click();
    await page.locator(`text="Testnet"`).click();
    await page.goto('https://leather.io');
    await page.waitForLoadState('networkidle');
  });

  test('that the bitcoin contract offer is properly displayed', async ({ page, context }) => {
    const expectedOfferorName = 'DLC.Link';
    const expectedLockAmount = '0.0001 BTC';
    const expectedExpirationDate = '10/17/2023';

    initiateOfferRequest(page)(requestParams);

    const popup = await context.waitForEvent('page');

    await popup.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 404,
        contentType: 'application/json',
        body: 'No contract found',
      });
    });

    await popup.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(storageMockResponse200),
      });
    });

    await popup.route(
      'https://blockstream.info/testnet/api/tx/1464ffac275caa89d548ab5ec4de821a11083fb3c39d8f014b5195a8b89ab9c0',
      route => {
        route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(blockchainMockResponse),
        });
      }
    );

    const offerorText = popup.getByTestId(
      BitcoinContractRequestSelectors.BitcoinContractOfferorText
    );
    const isOfferorTextVisible = await offerorText.isVisible();
    const offerorTextContent = await offerorText.innerText();
    const lockAmount = await popup
      .getByTestId(BitcoinContractRequestSelectors.BitcoinContractLockAmount)
      .innerText();
    const expirationDate = await popup
      .getByTestId(BitcoinContractRequestSelectors.BitcoinContractExpirationDate)
      .innerText();

    test.expect(isOfferorTextVisible).toBeTruthy();
    test.expect(offerorTextContent).toContain(expectedOfferorName);
    test.expect(lockAmount).toEqual(expectedLockAmount);
    test.expect(expirationDate).toEqual(expectedExpirationDate);

    await popup.close();
  });

  test('that user can reject a bitcoin contract offer', async ({ page, context }) => {
    const [result] = await Promise.all([
      initiateOfferRequest(page)(requestParams),
      clickReject(context),
    ]);
    await page.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 404,
        contentType: 'application/json',
        body: 'No contract found',
      });
    });

    await page.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(storageMockResponse200),
      });
    });

    await page.route(
      'https://blockstream.info/testnet/api/tx/1464ffac275caa89d548ab5ec4de821a11083fb3c39d8f014b5195a8b89ab9c0',
      route => {
        route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(blockchainMockResponse),
        });
      }
    );

    delete result.id;

    test.expect(result).toEqual({
      jsonrpc: '2.0',
      error: {
        code: 4001,
        message: 'Bitcoin Contract offer was rejected',
      },
    });
  });

  test(`that user can't accept a bitcoin contract offer without sufficient bitcoin'`, async ({
    page,
    context,
  }) => {
    initiateOfferRequest(page)(requestParams);

    const popup = await context.waitForEvent('page');

    await popup.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 404,
        contentType: 'application/json',
        body: 'No contract found',
      });
    });

    await popup.route('https://devnet.dlc.link/storage-api/contracts', route => {
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(storageMockResponse200),
      });
    });

    await popup.route(
      'https://blockstream.info/testnet/api/tx/1464ffac275caa89d548ab5ec4de821a11083fb3c39d8f014b5195a8b89ab9c0',
      route => {
        route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(blockchainMockResponse),
        });
      }
    );
    await popup.waitForTimeout(500);


    const acceptButton = popup.getByTestId(
      BitcoinContractRequestSelectors.BitcoinContractSignButton
    );

    const isAcceptButtonDisabled = await acceptButton.isDisabled();

    test.expect(isAcceptButtonDisabled).toBeTruthy();

    await popup.close();
  });
});
